// client/src/pages/Home.vue
<template>
  <div class="min-h-screen bg-gray-50 dark:bg-gray-900">
    <Header 
      :progress="progress" 
      @save="handleSave" 
    />
    
    <div class="flex">
      <!-- 左侧导航 -->
      <div class="w-80 bg-white dark:bg-gray-800 shadow-sm">
        <StepNavigation 
          :steps="steps"
          :activeStep="activeStep"
          @step-change="handleStepChange"
        />
      </div>
      
      <!-- 主要内容区域 -->
      <div class="flex-1 p-6">
        <div class="max-w-4xl mx-auto">
          <!-- 动态组件渲染 -->
          <component 
            :is="currentStepComponent"
            :data="campaignData"
            @change="handleDataChange"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import Header from '../components/Header.vue'
import StepNavigation from '../components/StepNavigation.vue'
import MarketingGoals from '../components/MarketingGoals.vue'
import PromotionScenario from '../components/PromotionScenario.vue'
import ProductSettings from '../components/ProductSettings.vue'
import UserTargeting from '../components/UserTargeting.vue'
import BudgetSchedule from '../components/BudgetSchedule.vue'
import DataPreview from '../components/DataPreview.vue'

import type { CampaignData } from '../lib/types'

// 步骤配置
const steps = [
  { id: 1, name: '营销目标' },
  { id: 2, name: '推广场景' },
  { id: 3, name: '商品设置' },
  { id: 4, name: '定向设置' },
  { id: 5, name: '预算投放' },
  { id: 6, name: '数据预览' }
]

// 响应式数据
const activeStep = ref(1)
const campaignData = ref<CampaignData>({
  name: '',
  marketingGoal: '',
  optimizationTarget: '',
  priority: '',
  promotionScenario: '',
  placements: [],
  deviceTypes: [],
  productId: null,
  originalPrice: 0,
  currentPrice: 0,
  hasTimeLimitedDiscount: false,
  discountPercentage: 0,
  hasFullReduction: false,
  fullReductionThreshold: 0,
  fullReductionAmount: 0,
  ageRange: '',
  gender: '',
  location: '',
  interests: [],
  behaviors: [],
  campaignType: '',
  startTime: null,
  endTime: null,
  totalBudget: 0,
  dailyBudget: 0,
  biddingStrategy: '',
  clickBid: 0,
  weeklySchedule: [false, false, false, false, false, false, false],
  status: 'draft'
})

// 计算当前步骤组件
const currentStepComponent = computed(() => {
  const componentMap: Record<number, any> = {
    1: MarketingGoals,
    2: PromotionScenario,
    3: ProductSettings,
    4: UserTargeting,
    5: BudgetSchedule,
    6: DataPreview
  }
  return componentMap[activeStep.value]
})

// 计算进度
const progress = computed(() => {
  return (activeStep.value / steps.length) * 100
})

// 获取活动数据
const { data: campaigns, isLoading, error } = useQuery({
  queryKey: ['campaigns'],
  queryFn: async () => {
    const response = await fetch('/api/campaigns')
    if (!response.ok) {
      throw new Error('Failed to fetch campaigns')
    }
    return response.json()
  }
})

// 事件处理
const handleStepChange = (stepId: number) => {
  activeStep.value = stepId
}

const handleDataChange = (updates: Partial<CampaignData>) => {
  campaignData.value = { ...campaignData.value, ...updates }
}

const handleSave = async () => {
  try {
    const response = await fetch('/api/campaigns', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(campaignData.value),
    })
    
    if (!response.ok) {
      throw new Error('保存失败')
    }
    
    console.log('活动保存成功')
  } catch (error) {
    console.error('保存活动时出错:', error)
  }
}

onMounted(() => {
  console.log('巨量千川教学系统已启动 - Vue 3版本')
})
</script>

// client/src/pages/home.tsx
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import Header from "@/components/header";
import StepNavigation from "@/components/step-navigation";
import MarketingGoals from "@/components/marketing-goals";
import PromotionScenario from "@/components/promotion-scenario";
import ProductSettings from "@/components/product-settings";
import UserTargeting from "@/components/user-targeting";
import BudgetSchedule from "@/components/budget-schedule";
import DataPreview from "@/components/data-preview";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";
import type { CampaignData } from "@/lib/types";

export default function Home() {
  const [activeStep, setActiveStep] = useState(0);
  const [campaignData, setCampaignData] = useState<CampaignData>({
    name: "新推广计划",
    marketingGoal: "",
    optimizationTarget: "展示量优化",
    priority: "均匀投放",
    promotionScenario: "",
    placements: [],
    deviceTypes: [],
    productId: null,
    originalPrice: 0,
    currentPrice: 0,
    hasTimeLimitedDiscount: false,
    discountPercentage: 0,
    hasFullReduction: false,
    fullReductionThreshold: 0,
    fullReductionAmount: 0,
    ageRange: "18-35",
    gender: "不限",
    location: "全国",
    interests: [],
    behaviors: [],
    campaignType: "持续投放",
    startTime: null,
    endTime: null,
    totalBudget: 10000,
    dailyBudget: 500,
    biddingStrategy: "智能出价",
    clickBid: 1.5,
    weeklySchedule: [true, true, true, true, true, true, true],
    status: "draft",
  });

  const { toast } = useToast();

  const { data: campaigns = [] } = useQuery({
    queryKey: ["/api/campaigns"],
  });

  const steps = [
    { id: 0, name: "营销目标设置", component: MarketingGoals },
    { id: 1, name: "推广场景配置", component: PromotionScenario },
    { id: 2, name: "产品推广设置", component: ProductSettings },
    { id: 3, name: "用户定向设置", component: UserTargeting },
    { id: 4, name: "排期预算管理", component: BudgetSchedule },
    { id: 5, name: "数据预览", component: DataPreview },
  ];

  const handleStepChange = (stepId: number) => {
    setActiveStep(stepId);
  };

  const handleDataChange = (updates: Partial<CampaignData>) => {
    setCampaignData(prev => ({ ...prev, ...updates }));
  };

  const handleSaveDraft = async () => {
    try {
      await apiRequest("POST", "/api/campaigns", {
        ...campaignData,
        status: "draft",
      });
      toast({
        title: "保存成功",
        description: "草稿已保存",
      });
    } catch (error) {
      toast({
        title: "保存失败",
        description: "请检查网络连接后重试",
        variant: "destructive",
      });
    }
  };

  const handleSubmit = async () => {
    try {
      await apiRequest("POST", "/api/campaigns", {
        ...campaignData,
        status: "submitted",
      });
      toast({
        title: "提交成功",
        description: "推广计划已提交",
      });
    } catch (error) {
      toast({
        title: "提交失败",
        description: "请检查所有必填信息后重试",
        variant: "destructive",
      });
    }
  };

  const CurrentStepComponent = steps[activeStep].component;
  const completedSteps = activeStep;
  const progress = ((completedSteps + 1) / steps.length) * 100;

  return (
    <div className="bg-gray-50 min-h-screen">
      <Header progress={progress} onSave={handleSaveDraft} />
      
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex gap-8">
          <StepNavigation
            steps={steps}
            activeStep={activeStep}
            onStepChange={handleStepChange}
          />
          
          <div className="flex-1">
            <CurrentStepComponent
              data={campaignData}
              onChange={handleDataChange}
            />
            
            <div className="mt-8 flex justify-end space-x-4">
              <Button
                variant="outline"
                onClick={handleSaveDraft}
              >
                保存草稿
              </Button>
              <Button
                variant="secondary"
                onClick={() => {
                  toast({
                    title: "预览效果",
                    description: "预览功能正在开发中",
                  });
                }}
              >
                预览效果
              </Button>
              <Button
                onClick={handleSubmit}
                disabled={!campaignData.marketingGoal || !campaignData.promotionScenario}
              >
                提交配置
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
