// client/src/components/BudgetSchedule.vue
<template>
  <div class="space-y-6">
    <div>
      <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-2">
        预算与投放设置
      </h2>
      <p class="text-gray-600 dark:text-gray-400">
        配置投放预算、时间和出价策略
      </p>
    </div>

    <div class="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm">
      <div class="space-y-6">
        <!-- 活动类型 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
            活动类型
          </label>
          <div class="flex space-x-4">
            <label class="flex items-center">
              <input
                v-model="localData.campaignType"
                @change="updateData"
                type="radio"
                value="continuous"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-900 dark:text-white">长期投放</span>
            </label>
            <label class="flex items-center">
              <input
                v-model="localData.campaignType"
                @change="updateData"
                type="radio"
                value="scheduled"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-900 dark:text-white">定时投放</span>
            </label>
          </div>
        </div>

        <!-- 投放时间 -->
        <div v-if="localData.campaignType === 'scheduled'" class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
              开始时间
            </label>
            <input
              v-model="startTimeString"
              @change="updateStartTime"
              type="datetime-local"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
              结束时间
            </label>
            <input
              v-model="endTimeString"
              @change="updateEndTime"
              type="datetime-local"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
            />
          </div>
        </div>

        <!-- 预算设置 -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
              总预算 (¥)
            </label>
            <input
              v-model.number="localData.totalBudget"
              @input="updateData"
              type="number"
              min="0"
              step="0.01"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
              日预算 (¥)
            </label>
            <input
              v-model.number="localData.dailyBudget"
              @input="updateData"
              type="number"
              min="0"
              step="0.01"
              class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
            />
          </div>
        </div>

        <!-- 出价策略 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
            出价策略
          </label>
          <select
            v-model="localData.biddingStrategy"
            @change="updateData"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
          >
            <option value="">请选择出价策略</option>
            <option value="auto">自动出价</option>
            <option value="manual">手动出价</option>
            <option value="target_cost">目标成本</option>
            <option value="target_roas">目标ROAS</option>
          </select>
        </div>

        <!-- 手动出价 -->
        <div v-if="localData.biddingStrategy === 'manual'">
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
            点击出价 (¥)
          </label>
          <input
            v-model.number="localData.clickBid"
            @input="updateData"
            type="number"
            min="0"
            step="0.01"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
          />
        </div>

        <!-- 投放时段 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-3">
            投放时段
          </label>
          <div class="grid grid-cols-7 gap-2">
            <div 
              v-for="(day, index) in weekDays" 
              :key="index"
              class="text-center"
            >
              <label class="block">
                <input
                  v-model="localData.weeklySchedule[index]"
                  @change="updateData"
                  type="checkbox"
                  class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
                />
                <span class="block text-xs text-gray-900 dark:text-white mt-1">{{ day }}</span>
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import type { CampaignData } from '../lib/types'

interface Props {
  data: CampaignData
}

const props = defineProps<Props>()
const emit = defineEmits<{
  change: [updates: Partial<CampaignData>]
}>()

const localData = ref({ ...props.data })

const weekDays = ['周一', '周二', '周三', '周四', '周五', '周六', '周日']

// 时间格式转换
const startTimeString = computed({
  get: () => localData.value.startTime ? new Date(localData.value.startTime).toISOString().slice(0, 16) : '',
  set: (value: string) => {
    localData.value.startTime = value ? new Date(value) : null
    updateData()
  }
})

const endTimeString = computed({
  get: () => localData.value.endTime ? new Date(localData.value.endTime).toISOString().slice(0, 16) : '',
  set: (value: string) => {
    localData.value.endTime = value ? new Date(value) : null
    updateData()
  }
})

const updateStartTime = (event: Event) => {
  const target = event.target as HTMLInputElement
  localData.value.startTime = target.value ? new Date(target.value) : null
  updateData()
}

const updateEndTime = (event: Event) => {
  const target = event.target as HTMLInputElement
  localData.value.endTime = target.value ? new Date(target.value) : null
  updateData()
}

const updateData = () => {
  emit('change', localData.value)
}

watch(() => props.data, (newData) => {
  localData.value = { ...newData }
}, { deep: true })
</script>

// client/src/components/budget-schedule.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Cell, Pie, PieChart, ResponsiveContainer } from "recharts";
import type { CampaignData } from "@/lib/types";

interface BudgetScheduleProps {
  data: CampaignData;
  onChange: (updates: Partial<CampaignData>) => void;
}

const budgetData = [
  { name: "直播推广", value: 60, color: "#1E40AF" },
  { name: "视频推广", value: 30, color: "#7C3AED" },
  { name: "信息流推广", value: 10, color: "#F59E0B" },
];

const weekDays = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"];

export default function BudgetSchedule({ data, onChange }: BudgetScheduleProps) {
  const handleScheduleToggle = (dayIndex: number) => {
    const newSchedule = [...data.weeklySchedule];
    newSchedule[dayIndex] = !newSchedule[dayIndex];
    onChange({ weeklySchedule: newSchedule });
  };

  const formatDateTime = (date: Date | null) => {
    if (!date) return "";
    return date.toISOString().slice(0, 16);
  };

  const parseDateTime = (dateString: string) => {
    return dateString ? new Date(dateString) : null;
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-xl">排期预算管理</CardTitle>
        <p className="text-sm text-gray-600">设置投放时间和预算分配策略</p>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Schedule Settings */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">投放时间</h3>
            <div className="space-y-4">
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">投放周期</Label>
                <RadioGroup
                  value={data.campaignType}
                  onValueChange={(value) => onChange({ campaignType: value })}
                  className="flex space-x-4"
                >
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="持续投放" id="continuous" />
                    <Label htmlFor="continuous">持续投放</Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="定期投放" id="scheduled" />
                    <Label htmlFor="scheduled">定期投放</Label>
                  </div>
                </RadioGroup>
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-sm font-medium text-gray-700 mb-2">开始时间</Label>
                  <Input
                    type="datetime-local"
                    value={formatDateTime(data.startTime)}
                    onChange={(e) => onChange({ startTime: parseDateTime(e.target.value) })}
                  />
                </div>
                <div>
                  <Label className="text-sm font-medium text-gray-700 mb-2">结束时间</Label>
                  <Input
                    type="datetime-local"
                    value={formatDateTime(data.endTime)}
                    onChange={(e) => onChange({ endTime: parseDateTime(e.target.value) })}
                  />
                </div>
              </div>
              
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">投放时段</Label>
                <div className="grid grid-cols-7 gap-1 text-xs mb-2">
                  {weekDays.map((day, index) => (
                    <div key={day} className="text-center p-1">{day}</div>
                  ))}
                </div>
                <div className="grid grid-cols-7 gap-1">
                  {data.weeklySchedule.map((active, index) => (
                    <button
                      key={index}
                      onClick={() => handleScheduleToggle(index)}
                      className={`h-8 rounded transition-colors ${
                        active ? "bg-primary" : "bg-gray-200"
                      }`}
                    />
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Budget Settings */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">预算设置</h3>
            <div className="space-y-4">
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">总预算</Label>
                <div className="relative">
                  <span className="absolute left-3 top-2 text-gray-500">¥</span>
                  <Input
                    type="number"
                    value={data.totalBudget}
                    onChange={(e) => onChange({ totalBudget: parseFloat(e.target.value) || 0 })}
                    className="pl-8"
                  />
                </div>
              </div>
              
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">日预算</Label>
                <div className="relative">
                  <span className="absolute left-3 top-2 text-gray-500">¥</span>
                  <Input
                    type="number"
                    value={data.dailyBudget}
                    onChange={(e) => onChange({ dailyBudget: parseFloat(e.target.value) || 0 })}
                    className="pl-8"
                  />
                </div>
              </div>
              
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">出价策略</Label>
                <Select
                  value={data.biddingStrategy}
                  onValueChange={(value) => onChange({ biddingStrategy: value })}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="智能出价">智能出价</SelectItem>
                    <SelectItem value="手动出价">手动出价</SelectItem>
                    <SelectItem value="目标成本出价">目标成本出价</SelectItem>
                    <SelectItem value="目标转化出价">目标转化出价</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">单次点击出价</Label>
                <div className="relative">
                  <span className="absolute left-3 top-2 text-gray-500">¥</span>
                  <Input
                    type="number"
                    step="0.1"
                    value={data.clickBid}
                    onChange={(e) => onChange({ clickBid: parseFloat(e.target.value) || 0 })}
                    className="pl-8"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Budget Allocation Chart */}
        <div className="mt-6 p-4 bg-gray-50 rounded-lg">
          <h4 className="font-medium text-gray-900 mb-3">预算分配预览</h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={budgetData}
                    cx="50%"
                    cy="50%"
                    innerRadius={40}
                    outerRadius={80}
                    paddingAngle={5}
                    dataKey="value"
                  >
                    {budgetData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="space-y-3">
              {budgetData.map((item) => (
                <div key={item.name} className="flex justify-between items-center">
                  <div className="flex items-center space-x-2">
                    <div
                      className="w-3 h-3 rounded-full"
                      style={{ backgroundColor: item.color }}
                    />
                    <span className="text-sm text-gray-600">{item.name}</span>
                  </div>
                  <span className="text-sm font-medium text-gray-900">
                    ¥{((data.totalBudget * item.value) / 100).toLocaleString()} ({item.value}%)
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
