// client/src/components/UserTargeting.vue
<template>
  <div class="space-y-6">
    <div>
      <h2 class="text-2xl font-bold text-gray-900 dark:text-white mb-2">
        用户定向设置
      </h2>
      <p class="text-gray-600 dark:text-gray-400">
        精准定向目标用户群体，提升广告投放效果
      </p>
    </div>

    <div class="bg-white dark:bg-gray-800 rounded-lg p-6 shadow-sm">
      <div class="space-y-6">
        <!-- 年龄范围 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
            年龄范围
          </label>
          <select
            v-model="localData.ageRange"
            @change="updateData"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
          >
            <option value="">请选择年龄范围</option>
            <option value="18-25">18-25岁</option>
            <option value="26-35">26-35岁</option>
            <option value="36-45">36-45岁</option>
            <option value="46-55">46-55岁</option>
            <option value="55+">55岁以上</option>
          </select>
        </div>

        <!-- 性别 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
            性别
          </label>
          <div class="flex space-x-4">
            <label class="flex items-center">
              <input
                v-model="localData.gender"
                @change="updateData"
                type="radio"
                value=""
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-900 dark:text-white">不限</span>
            </label>
            <label class="flex items-center">
              <input
                v-model="localData.gender"
                @change="updateData"
                type="radio"
                value="male"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-900 dark:text-white">男性</span>
            </label>
            <label class="flex items-center">
              <input
                v-model="localData.gender"
                @change="updateData"
                type="radio"
                value="female"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-900 dark:text-white">女性</span>
            </label>
          </div>
        </div>

        <!-- 地理位置 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-2">
            地理位置
          </label>
          <select
            v-model="localData.location"
            @change="updateData"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:text-white"
          >
            <option value="">不限地区</option>
            <option value="beijing">北京</option>
            <option value="shanghai">上海</option>
            <option value="guangzhou">广州</option>
            <option value="shenzhen">深圳</option>
            <option value="hangzhou">杭州</option>
            <option value="tier1">一线城市</option>
            <option value="tier2">二线城市</option>
            <option value="tier3">三线城市</option>
          </select>
        </div>

        <!-- 兴趣标签 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-3">
            兴趣标签
          </label>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
            <label 
              v-for="interest in availableInterests" 
              :key="interest"
              class="flex items-center p-2 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer"
            >
              <input
                v-model="localData.interests"
                @change="updateData"
                type="checkbox"
                :value="interest"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-900 dark:text-white">{{ interest }}</span>
            </label>
          </div>
        </div>

        <!-- 行为特征 -->
        <div>
          <label class="block text-sm font-medium text-gray-900 dark:text-white mb-3">
            行为特征
          </label>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-3">
            <label 
              v-for="behavior in availableBehaviors" 
              :key="behavior"
              class="flex items-center p-2 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer"
            >
              <input
                v-model="localData.behaviors"
                @change="updateData"
                type="checkbox"
                :value="behavior"
                class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500"
              />
              <span class="ml-2 text-sm text-gray-900 dark:text-white">{{ behavior }}</span>
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import type { CampaignData } from '../lib/types'

interface Props {
  data: CampaignData
}

const props = defineProps<Props>()
const emit = defineEmits<{
  change: [updates: Partial<CampaignData>]
}>()

const localData = ref({ ...props.data })

const availableInterests = [
  '时尚服装', '美妆护肤', '数码科技', '家居用品',
  '运动健身', '旅游出行', '美食餐饮', '母婴亲子',
  '教育培训', '金融理财', '汽车', '房产装修'
]

const availableBehaviors = [
  '经常网购', '喜欢直播', '关注优惠', '冲动消费',
  '品质导向', '价格敏感', '社交分享', '评价参考'
]

const updateData = () => {
  emit('change', localData.value)
}

watch(() => props.data, (newData) => {
  localData.value = { ...newData }
}, { deep: true })
</script>

// client/src/components/user-targeting.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Slider } from "@/components/ui/slider";
import type { CampaignData } from "@/lib/types";

interface UserTargetingProps {
  data: CampaignData;
  onChange: (updates: Partial<CampaignData>) => void;
}

const interestOptions = [
  "美妆护肤",
  "数码产品",
  "服装配饰",
  "健康养生",
  "运动健身",
  "家居生活",
];

const behaviorOptions = [
  "经常观看直播",
  "有购买行为",
  "活跃用户",
  "高价值用户",
];

export default function UserTargeting({ data, onChange }: UserTargetingProps) {
  const handleInterestToggle = (interest: string) => {
    const newInterests = data.interests.includes(interest)
      ? data.interests.filter(i => i !== interest)
      : [...data.interests, interest];
    onChange({ interests: newInterests });
  };

  const handleBehaviorToggle = (behavior: string) => {
    const newBehaviors = data.behaviors.includes(behavior)
      ? data.behaviors.filter(b => b !== behavior)
      : [...data.behaviors, behavior];
    onChange({ behaviors: newBehaviors });
  };

  const handleAgeRangeChange = (value: number[]) => {
    onChange({ ageRange: `${value[0]}-${value[1]}` });
  };

  const getAgeRange = () => {
    const [min, max] = data.ageRange.split('-').map(Number);
    return [min || 18, max || 65];
  };

  // Calculate audience metrics
  const coverageCount = 2300000;
  const matchRate = 85;
  const competitionLevel = "中等";

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-xl">用户定向设置</CardTitle>
        <p className="text-sm text-gray-600">精准定向目标用户，提升推广效果</p>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Demographics */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">基础信息</h3>
            <div className="space-y-4">
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">年龄范围</Label>
                <div className="mt-2">
                  <Slider
                    value={getAgeRange()}
                    onValueChange={handleAgeRangeChange}
                    max={65}
                    min={18}
                    step={1}
                    className="w-full"
                  />
                  <div className="flex justify-between text-sm text-gray-600 mt-1">
                    <span>18岁</span>
                    <span>{data.ageRange}岁</span>
                    <span>65岁</span>
                  </div>
                </div>
              </div>
              
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">性别</Label>
                <RadioGroup
                  value={data.gender}
                  onValueChange={(value) => onChange({ gender: value })}
                  className="flex space-x-4"
                >
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="不限" id="gender-all" />
                    <Label htmlFor="gender-all">不限</Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="男性" id="gender-male" />
                    <Label htmlFor="gender-male">男性</Label>
                  </div>
                  <div className="flex items-center space-x-2">
                    <RadioGroupItem value="女性" id="gender-female" />
                    <Label htmlFor="gender-female">女性</Label>
                  </div>
                </RadioGroup>
              </div>
              
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">地域选择</Label>
                <Select value={data.location} onValueChange={(value) => onChange({ location: value })}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="全国">全国</SelectItem>
                    <SelectItem value="一线城市">一线城市</SelectItem>
                    <SelectItem value="二线城市">二线城市</SelectItem>
                    <SelectItem value="三四线城市">三四线城市</SelectItem>
                    <SelectItem value="自定义地区">自定义地区</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </div>

          {/* Interests */}
          <div>
            <h3 className="text-lg font-medium text-gray-900 mb-4">兴趣标签</h3>
            <div className="space-y-4">
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">消费兴趣</Label>
                <div className="flex flex-wrap gap-2">
                  {interestOptions.map((interest) => (
                    <button
                      key={interest}
                      onClick={() => handleInterestToggle(interest)}
                      className={`interest-tag ${
                        data.interests.includes(interest) ? 'selected' : ''
                      }`}
                    >
                      {interest}
                    </button>
                  ))}
                </div>
              </div>
              
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-2">行为特征</Label>
                <div className="space-y-2">
                  {behaviorOptions.map((behavior) => (
                    <div key={behavior} className="flex items-center space-x-2">
                      <Checkbox
                        id={behavior}
                        checked={data.behaviors.includes(behavior)}
                        onCheckedChange={() => handleBehaviorToggle(behavior)}
                      />
                      <Label htmlFor={behavior} className="text-sm text-gray-600">
                        {behavior}
                      </Label>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Audience Preview */}
        <div className="mt-6 p-4 bg-blue-50 rounded-lg">
          <h4 className="font-medium text-gray-900 mb-3">受众预览</h4>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="text-center">
              <div className="text-2xl font-bold text-primary">
                {(coverageCount / 1000000).toFixed(1)}M
              </div>
              <div className="text-sm text-gray-600">预估覆盖人数</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-secondary">{matchRate}%</div>
              <div className="text-sm text-gray-600">匹配度</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-accent">{competitionLevel}</div>
              <div className="text-sm text-gray-600">竞争激烈程度</div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
